<?php
/**
 * settings.ini.php
 * 
 * Defines initialization settings for alder.
 * DO NOT edit this file, to override these settings use settings.local.ini.php instead.
 * Any changes in the local ini file will override the settings found here.
 */

global $SETTINGS;

// tagged version
$SETTINGS['general']['application_name'] = 'alder';
$SETTINGS['general']['instance_name'] = $SETTINGS['general']['application_name'];
$SETTINGS['general']['version'] = '2.10';
$SETTINGS['general']['build'] = '424dc2d';

// the location of alder internal path
$SETTINGS['path']['APPLICATION'] = str_replace( '/settings.ini.php', '', __FILE__ );

// the directory where images are located
$SETTINGS['path']['IMAGES'] = NULL;
$SETTINGS['url']['IMAGES'] = NULL;

// the directory where supplementary images are located
$SETTINGS['path']['SUPPLEMENTARY'] = NULL;

// the location of a keyfile used for Apex SSH commands
$SETTINGS['apex']['keyfile'] = $SETTINGS['path']['APPLICATION'].'/doc/apex_key';

// the password used when connecting to all Apex databases
$SETTINGS['apex']['db_password'] = '';

// the timeout used when communicating with an Apex server (in seconds)
$SETTINGS['apex']['timeout'] = 5;

// the maximum number of batched analysis uploads to perform at a time
$SETTINGS['apex']['batch_size'] = 20;

// how many times to try uploading a file before giving up
$SETTINGS['apex']['tries'] = 3;

// various paths on Apex servers
$SETTINGS['apex']['dgate_in'] = 'C:\dicomserverIN';
$SETTINGS['apex']['dgate_out'] = 'C:\dicomserverOUT';
$SETTINGS['apex']['incoming'] = 'E:\incoming';
$SETTINGS['apex']['outgoing'] = 'E:\outgoing';
$SETTINGS['apex']['qdr_data'] = 'E:\QDR\Data';
