#!/usr/bin/php
<?php
/**
 * Calculates T and Z scores
 * 
 * The script expects the only argument to be a JSON file containing the apex data of a single scan
 * Author: Patrick Emond <emondpd@mcmaster.ca>
 */

if( '/aux' == substr( getcwd(), -4 ) ) chdir( '..' );

require_once 'settings.ini.php';
require_once 'settings.local.ini.php';
require_once $SETTINGS['path']['CENOZO'].'/src/arguments.class.php';
require_once $SETTINGS['path']['CENOZO'].'/src/initial.class.php';
require_once $SETTINGS['path']['CENOZO'].'/src/base_object.class.php';
require_once 'src/business/tz_reference.class.php';
require_once $SETTINGS['path']['CENOZO'].'/src/singleton.class.php';
require_once $SETTINGS['path']['CENOZO'].'/src/lib.class.php';
require_once $SETTINGS['path']['CENOZO'].'/src/log.class.php';
require_once $SETTINGS['path']['CENOZO'].'/src/util.class.php';
require_once $SETTINGS['path']['CENOZO'].'/src/exception/base_exception.class.php';
require_once $SETTINGS['path']['CENOZO'].'/src/exception/system.class.php';
require_once 'src/util.class.php';

$initial = new \cenozo\initial( true );

$arguments = new arguments( __FILE__ );
$arguments->set_description( "Calculates T/Z scores and PR/AM values from Apex data stored in a JSON file." );
$arguments->add_option(
  's', // short name
  'side', // long name
  'The side of the scan: left or right (used for forearm and hip only)',
  true, // must include value
  'none' // default
);
$arguments->add_option(
  't', // short name
  'type', // long name
  'The type of scan: hip, spine, forearm, lateral or wbody',
  true, // must include value
  'spine' // default
);
$arguments->add_input(
  'FILENAME',
  'The name of the JSON file containing Apex scan data'
);

$args = $arguments->parse_arguments( $argv );
$side = $args['option_list']['side'];
$type = $args['option_list']['type'];
$filename = $args['input_list']['FILENAME'];

$tz_reference = new \alder\business\tz_reference();
$contents = file_get_contents( $filename );
$apex_data = json_decode( $contents );

// if a single object is passed then turn it into a single element array
if( is_object( $apex_data ) ) $apex_data = [$apex_data];

foreach( $apex_data as $index => $object )
{
  $score_data = $tz_reference->compute_tz_scores( $type, $side, (array)$object );

  // print the header
  if( 0 == $index ) printf( "%s\n", implode( ',', array_keys( $score_data ) ) );

  // print the data
  printf( "%s\n", implode( ',', array_values( $score_data ) ) );
}
