#!/usr/bin/php
<?php
/**
 * Calculates T and Z scores
 * 
 * The script expects the only argument to be a JSON file containing the apex data of a single scan
 * Author: Patrick Emond <emondpd@mcmaster.ca>
 */

if( '/aux' == substr( getcwd(), -4 ) ) chdir( '..' );

require_once 'settings.ini.php';
require_once 'settings.local.ini.php';
require_once $SETTINGS['path']['CENOZO'].'/src/initial.class.php';
require_once $SETTINGS['path']['CENOZO'].'/src/base_object.class.php';
require_once 'src/business/tz_reference.class.php';
require_once $SETTINGS['path']['CENOZO'].'/src/singleton.class.php';
require_once $SETTINGS['path']['CENOZO'].'/src/lib.class.php';
require_once $SETTINGS['path']['CENOZO'].'/src/log.class.php';
require_once $SETTINGS['path']['CENOZO'].'/src/util.class.php';
require_once $SETTINGS['path']['CENOZO'].'/src/exception/base_exception.class.php';
require_once $SETTINGS['path']['CENOZO'].'/src/exception/system.class.php';
require_once 'src/util.class.php';

$initial = new \cenozo\initial( true );

$tz_reference = new \alder\business\tz_reference();
$tz_reference::$debug = true;
$contents = file_get_contents( $argv[1] );
$apex_data = (array) json_decode( $contents );
$tz_reference->compute_tz_scores( $apex_data );

$tz_data = [];
foreach( $apex_data as $column => $value )
{
  if( preg_match( '/_[tz]$/', $column ) )
  {
    printf( "%s: %s\n", $column, $value );
  }
}
