CREATE TABLE annotation (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  update_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  create_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  analysis_id INT(10) UNSIGNED NOT NULL,
  type ENUM("arrow", "ellipse") NOT NULL,
  x0 FLOAT NOT NULL,
  y0 FLOAT NOT NULL,
  x1 FLOAT NOT NULL,
  y1 FLOAT NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_analysis_id (analysis_id ASC),
  CONSTRAINT fk_arrow_analysis_id
    FOREIGN KEY (analysis_id)
    REFERENCES alder.analysis (id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;
