SELECT "Creating new ellipse table" AS "";

CREATE TABLE IF NOT EXISTS ellipse (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  update_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  create_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  review_id INT(10) UNSIGNED NOT NULL,
  x FLOAT NOT NULL,
  y FLOAT NOT NULL,
  rx FLOAT NOT NULL,
  ry FLOAT NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_review_id (review_id ASC),
  CONSTRAINT fk_ellipse_review_id
    FOREIGN KEY (review_id)
    REFERENCES review (id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
