SELECT "Creating new image table" AS "";

CREATE TABLE IF NOT EXISTS image (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  update_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  create_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  exam_id INT(10) UNSIGNED NOT NULL,
  path VARCHAR(255) NOT NULL,
  note TEXT NULL DEFAULT NULL,
  feedback TEXT NULL DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX fk_exam_id (exam_id ASC),
  UNIQUE INDEX uq_path (path ASC),
  CONSTRAINT fk_image_exam_id
    FOREIGN KEY (exam_id)
    REFERENCES exam (id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
